stages:
  - test

variables:
  GO_PACKAGE: github.com/trevor403/go-openvpn-static
  GIT_CLONE_PATH: /home/gitlab-runner/go/src/$GO_PACKAGE
  GOFLAGS: "-count=1" # Supersedes GOCACHE=off, see: https://github.com/golang/go/issues/29378#issuecomment-449383809

checks:
  stage: test
  tags: [go]
  script: go run mage.go -v Check

test:
  stage: test
  tags: [go]
  script: go run mage.go Test

check-binaries:
  stage: test
  tags: [go]
  script: ./check-all.sh

go-report:
  stage: test
  tags: [go]
  script: go run mage.go GoReport